### ISSUE TITLE
Initial Trench Placement creates solid object

### ISSUE THREAD

**Issue by MonocledBadger** [gruppe-adler/grad_trenches#102]
When placing a trench, other clients can see a huge version of the trench in the starting placement position. This huge version of the trench is a solid and impassable object to everyone aside from the digger - who does not see the trench.

When the client placing the trench moves forward - the trench remains behind until they confirm placement and begin digging, at which point normal interactions occur and the Massive trench is removed.

Version used: v1.6.5.0
This issue has existed since at least v1.6.4.0

Reproduction Steps (Requires 2 people)
1. Have someone use ACE Interaction to choose placement for a GRAD Trench.
2. Do not confirm placement of trench.
3. Have 2nd client (person) verify they can see a large version of the trench and are unable to shoot/walk through it as it is a solid object.

Can provide video example if needed.

**Comment by nomisum** [comment]
I guess collision disabling is not really working here
https://github.com/gruppe-adler/grad_trenches/blob/master/addons/functions/functions/fnc_placeTrench.sqf#L34

Why the trench does not move along I have no spontaneous idea.

**Comment by MonocledBadger** [comment]
It's also the case the trench is several times larger than a dug version (At least visibly dug).

VIdeo example here:
https://youtu.be/EbkqlRwI84o

**Comment by AdlerSalbei** [comment]
Thanks for the bug report, I'll have a loo´k
