### ISSUE TITLE
Stamina Bug with Assisting 

### ISSUE THREAD

**Issue by MonocledBadger** [gruppe-adler/grad_trenches#104]
**Version used:** 1.6.7.0
**Map used:** Altis (Although this has been reported across various maps in my community)

**Issue:** 
Trench assistance in various forms causes a bug with stamina to drain even when underweight and on combat pace and it struggles to regen. This only affects the assister and not the digger. From my testing there are 3 cases where this bug occurs.

**Cases**
1) Assisting with digging a trench and stopping assistance before it completes.
2) Assisting with undigging a trench and stopping assistance it before it completes.
3) Assisting with undigging a trench and assisting until it is fully undug.

Digging and undigging a trench by yourself is fine as is assisting with digging a trench and completing it (not cancelling).

**Reproduction Steps**
Reproduction Steps for Case 1 (Requires 2 people - Digger + Assistant)
1. Have the Digger begin digging a GRAD Trench.
2. Have the assistant help dig through ACE Interaction.
3. After some time before the trench has completed, have the assistant cancel the help dig process by pressing the Escape Key.
4. Run around with minimal load and on combat pace to test stamina drain (this may take a few seconds to be noticeable).

Reproduction Steps for Case 2 (Requires 2 people - Digger + Assistant)
1. Have the Digger dig a GRAD Trench.
2. Have the Digger begin undigging the Trench.
3. Have the assistant help undig the Trench through ACE Interaction.
4. After some time before the trench has been fully undug, have the assistant cancel the help dig process by pressing the Escape Key.
5. Run around with minimal load and on combat pace to test stamina drain (this may take a few seconds to be noticeable).

Reproduction Steps for Case 3 (Requires 2 people - Digger + Assistant)
1. Have the Digger dig a GRAD Trench.
2. Have the Digger begin undigging the Trench.
3. Have the assistant help undig the Trench through ACE Interaction.
3. Have the assistant continue the assisting the undig process until the trench has been fully removed.
4. Run around with minimal load and on combat pace to test stamina drain (this may take a few seconds to be noticeable).

**Comment by AdlerSalbei** [comment]
THanks for the great bug report. I'll have a look at it.
