### ISSUE TITLE
Bushes (Camouflage) staying behind

### ISSUE THREAD

**Issue by Insane1626** [gruppe-adler/grad_trenches#107]
When you apply camo to trenches, if you dig the trench down with camo still on, the camo will not be removed with it.

![image_2021-05-06_212126](https://user-images.githubusercontent.com/83762970/117290327-03bb8f00-aeb1-11eb-933f-322d680471d5.png)

**Comment by AdlerSalbei** [comment]
Thanks for the Report. how did you remove the Trench?

**Comment by Insane1626** [comment]
Dug the trench down normal way. But didn't do the 'remove camo' option that was there as well.

**Comment by AdlerSalbei** [comment]
So you removed it per Ace Action?

**Comment by Insane1626** [comment]
By Ace interaction yes
