### ISSUE TITLE
Beketov Compatibility issue

### ISSUE THREAD

**Issue by Saborknight** [gruppe-adler/grad_trenches#110]
I don't know if this still applies, but the [GRAD Trenches - Beketov mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1852735669) basically just contains this:

```c
class CfgWorldsTextures
{
    class Beketov
	{
        surfaceTextureBasePath="RusLand\beketov_layer\Data\";
        suffix="co.paa";
        camouflageObjects[]={"ca\plants2\clutter\c_weed3.p3d"};
    };
};
```

Should this be changed in GRAD Trenches or...?

**Comment by AdlerSalbei** [comment]
Not my mod, sry can't help you with that.
