### ISSUE TITLE
[Feature Request] Handler for players when placing trenches

### ISSUE THREAD

**Issue by Buzztr0n** [gruppe-adler/grad_trenches#122]
Sorry if something like this already exists and I failed to find it:

Would love to see a handler like ACE3 did with the "Fortify Tool" (ace_fortify_fnc_addDeployHandler)
With that you can return TRUE/FALSE inside the handler to allow/disallow the placement of the object/trench. This is very useful for example to prevent anyone from building these inside any sort of restricted zones. Or e.g. prevent them from digging while enemies are extremely close, etc.

**Comment by AdlerSalbei** [comment]
Well, there is a variable that you can toggle that the system checks: https://github.com/gruppe-adler/grad_trenches/blob/master/addons/functions/initSettings.sqf#L2
