### ISSUE TITLE
[Bug] Trench preview's collision causes mayhem

### ISSUE THREAD

**Issue by IS4Code** [gruppe-adler/grad_trenches#125]
Tested on version 1.6.8.9.

We've got ourselves in a situation where the trench's preview model caused a vehicle to explode. It's unfortunate for this to be happening in otherwise such an amazing mod.

Steps to reproduce in multiplayer:

* Get someone in a vehicle on gunner and start shooting. There should be no driver in the vehicle.
* Let another player outside the vehicle select a trench and display the preview, and move towards the vehicle.
* The vehicle will be affected by the trench's collision, either being launched to heavens or slammed to hell, depending on your luck.

If there is a driver in the vehicle, it seems not to happen, as the driver (likely) has full control over the vehicle and doesn't let it explode. If there is no driver, anyone could synchronize the vehicle to explode with the preview model, as long as the vehicle's collision is triggered (via shooting or contact with another vehicle).

Steps to reproduce in singleplayer:

* Get an AI in a vehicle on gunner or driver and make it do something (drive or shoot).
* The rest same as above; the vehicle can be moved or destroyed by the preview model.

This is not something that should happen, the preview should have absolutely no collision (even though it is only a local object).

**Comment by nomisum** [comment]
thank you for the report.

looking at the code i see no quick fix for this. simulation is already disabled for the trench preview (& the same way ACE does it). no idea whats happening here. `enablesimulationglobal` should work for local objects too.

maybe @AdlerSalbei has an idea.

my only suggestion would be to try and use only a local `enableSimulation` command instead of serverEvent. maybe the global EH execution fails when the server does not know the object. this would mean the bug is inside ACE as well.

did you reproduce without grad trenches / only ACE by any chance @IllidanS4 ?

**Comment by AdlerSalbei** [comment]
You can not reproduce it with ACE. They are using a different system. But it is a quite interesting Issue. I'll have a lock at it.

**Comment by IllidanS4** [comment]
We had been using the trenches from ACE for years and I don't recall the bug ever happening, but I also can't say we've specifically tested that. By the way we are using [this version of ACE](https://steamcommunity.com/sharedfiles/filedetails/?id=1960252423) in case it would be relevant.

**Comment by IllidanS4** [comment]
Not sure if you had an idea how to fix this, but I don't think there is a good way to do this from script. It seems [`disableCollisionWith`](https://community.bistudio.com/wiki/disableCollisionWith) overwrites any previously set state, so using it could pose a danger for scripts that rely on this.

Why not simply create two models for each trench, one with and one without collision data? Then the preview could simply use the object without collision, and no need to try to come up with a script solution.

**Comment by nomisum** [comment]
thats how ace does it, certainly a viable approach

**Comment by IS4Code** [comment]
@AdlerSalbei Thank you for the update! Could you please point me to the commit where this was fixed?
