### ISSUE TITLE
[Feature Request] "Lock Texture" Function 

### ISSUE THREAD

**Issue by BulletsBreath** [gruppe-adler/grad_trenches#128]
Sometimes i'm struggeling a little bit with perfect positioning of your trenches in the editor, because if you move them a bit left or right they pick another ground texture that might exist on the ground, but stand out in a trench or emplacement i want to build. Would it be possible to add a "lock texture" box to the trench objects so you can place them on a surface with the texture you want, lock that texture and then move the trench a little without it chaning colors? Would be a really nice feature for building emplacements in the editor.

**Comment by AdlerSalbei** [comment]
I'll think about it, but no promises
