### ISSUE TITLE
Trenches on dedicated server not working

### ISSUE THREAD

**Issue by Warhammer47** [gruppe-adler/grad_trenches#130]
We, a community of 30+ players, can't use the trenches in a dedicated server. 
Although the trench option in the ACE menu apears, the animation and countdown bar does not apear.
The PBO works fine of SP and MP in local PCs.

**Comment by AdlerSalbei** [comment]
Have you tried IT with only cba, ace and trenches in mp?

**Comment by Warhammer47** [comment]
Ok the mod works by itself.
What seems to be the problem is when we use the PBOs in a private mod (a mod of multiples mods / PBOs inside) it does not work. We are now testing if it is:
1-Wrongly placed inside the private mod;
2-Is conflicting with another mod.

Either way the thread can be closed, thanks for the help

**Comment by AdlerSalbei** [comment]
You do now that you violate the license by doing that?

**Comment by Warhammer47** [comment]
Even in private/unlisted mods (not public on steam)? If so we will take action

**Comment by AdlerSalbei** [comment]
Yes

**Comment by Warhammer47** [comment]
Thanks for the info and sorry for violating the license
