### ISSUE TITLE
Northern Front Winter Terrain incompatibility

### ISSUE THREAD

**Issue by HombreII** [gruppe-adler/grad_trenches#133]
Tested Northern fronts terrains:
- Summa Winter
- Raate Road Winter
- Suursaari Winter

Trenches not compatible with snow terrain(?). Editor placed trenches correctly apply the ground texture, however the ACE3 self-interaction to dig said trenches in-game does not appear, neither does the interaction to remove trenches on editor placed ones.

**Comment by AdlerSalbei** [comment]
You can't dig on these surfaces because the dust value is 0 and it is not on the Whitelist. 

You need to add it to the DIG_SURFACE_WHITELIST for it to work.
