### ISSUE TITLE
cfgPatches bugs

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad_trenches#14]
* name is "grad_trenches_trenches" - PREFIX should be defined as "grad" instead of "grad_trenches"
* VERSION and VERSION_AR for VERSION_CONFIG macro are undefined
* REQUIRED_VERSION macro is undefined
* authors[] is empty

**Comment by chris579** [comment]
> name is "grad_trenches_trenches" - PREFIX should be defined as "grad" instead of "grad_trenches"

gruppe_adler_mod uses `x\grad\addons\*` therefore grad_trenches would have to be placed at the same location on P drive. This would merge these both repos. I will leave the path intact and are going to rename the component to `main` while splitting up assets and functions to different components.

Best case would be to to use `grad\<modname>\addons\*` for all GRAD mods so they are bundled at one place.

**Comment by chris579** [comment]
Resolved in dev branch.
