### ISSUE TITLE
Trench animation problem

### ISSUE THREAD

**Issue by AdabsurdumXML** [gruppe-adler/grad_trenches#140]
Currently there are problems with the trenching animation. As soon as you help another player with trenching, the animation that lifts the trench out of the ground is executed several times at once, which leads to extreme FPS drops and lags. The bar showing the progress of the trenching is shown, but the bar does not fill up with progress during the trenching. Also only for the player who helps trenching.

The problem only occurs with the player who helps the other player digging. If I place and build a trench myself, I don't have the problem.  It only ever occurs with the player who is helping to dig. I think the problem occurs since the last mod update, before that everything was fine.

**Comment by AdlerSalbei** [comment]
I think this is related to this issue: https://github.com/gruppe-adler/grad_trenches/issues/135

Will have a look at it, when I get home

**Comment by AdlerSalbei** [comment]
fixed with newest release
