### ISSUE TITLE
Issue with invisible Trench

### ISSUE THREAD

**Issue by FrostyGhost99** [gruppe-adler/grad_trenches#141]
This has been a recurring thing on my friend's Antistasi community version games, happens everytime we add in GRADS trenches to the modpack, we have ace and CBA_A3 also as recommended

**Comment by PulsarNeutronStar** [comment]
protip: Short Title, Long Description/Comment

**Comment by AdlerSalbei** [comment]
Have you tested it with out anti Stasi?
Does the Same Person initiate the digging?

**Comment by FrostyGhost99** [comment]
Yeah so we can build one trench and the next one we make becomes invisible and forms in a second instead of the time we've set for trenches to get built, this invisible trench has an ace interaction marker but you can't do anything to the invisible trench with ace interact. Need to test if this bug happens if you assist someone in digging or if it is a solo digging trench thing, will update you soon
