### ISSUE TITLE
Infinite Trench Construction Since ACE/CBA Update

### ISSUE THREAD

**Issue by SebayaKeto** [gruppe-adler/grad_trenches#145]
Hello GRAD Team,

Unfortunately since the latest ACE and CBA updates trenches are not working properly. Attempting to dig them will lock you into the UI infinitely with no construction happening. Cancelling animations does fix the issue but still without a trench being constructed.

**Comment by OverlordZorn** [comment]
server rpt and client rpt

**Comment by OverlordZorn** [comment]
Just tested on Editor Singleplayer - cannot reproduce the issue.

I asked an Antistasi Official server admin and they have not noticed any issues.

I lean out of the window and say: check if your mods on both server and clients are propperly installed and updated

**Comment by AdlerSalbei** [comment]
@SebayaKeto have you tested it, Independant of the Server?

**Comment by Jusiik** [comment]
Hello. We faced exactly the same issue with the latest ACE and CBA updates. It turned out that we had an older version(1.6.9.6) of Grad Trenches and updating it fixed all issues.
