### ISSUE TITLE
Add several camouflage stages

### ISSUE THREAD

**Issue by klemmchr** [gruppe-adler/grad_trenches#21]
Add different stages for camouflaging trenches. Could end up that trenches are fully covered by bushes.

**Comment by anfo55** [comment]
Good idea. When I was in my country's army reserve, we learned of different stages, like
1. Shell scrape. Shallow ditch that your body would lie in,
2. Stage 1 pit, perhaps what ACE/Grad trenches could be, about 500mm deep,
3. Stage 2 pit, deeper pit, sleeping bays added, not applicable to mod maybe,
4. Stage 3, covered by OHC (overhead concealment) with extra camo as @chris579 mentioned

**Comment by AdlerSalbei** [comment]
In mod
