### ISSUE TITLE
Bullet collision bug // OP trenches // Ugly texture

### ISSUE THREAD

**Issue by blackyesp** [gruppe-adler/grad_trenches#28]
@AdlerSalbei @chris579 Hello, i like your mod and appreciate the work. It's already implemented in my milsim clan and works fine. However my men conplained about enemies being able to shoot through the Giant Trench model. I tested it afterwards and in fact I've spotted a bullet collision bug using that model but only on certain parts of it. Haven't tried the Vehicle trench yet, but the default trenches work fine. Could you please fix this? 
:)

Update1:  Giant Trenches take a bit longer to fully spawn than the default bigger ones. Thats fine, but as soon as you place them it grants immediate cover to the player. If you compare it with the default ones that spawn slowly granting cover over the time, makes no sense at all and breaks immersion.  In other words, 1 second of Giant trench = 4-5 seconds of normal trench. You can just spawn it, cancel the digging and there you go. Some players already take advantage of it on my server. Could be nice to have them spawn slower :)

Update2: I noticed that some trenches spawn with an odd and ugly texture that doesn't match with the ground, like Beige with green spots. Very dryswamplike. Only using Altis and the ground texture was always different so I can't really tell anything else from my experience.

If you need any info, just add me on Steam: blackyesp

Alles gute!

**Comment by chris579** [comment]
Thanks for the report and welcome on GitHub. You don't have to mention us here, we'll see new issues anyway.

The giant trench model should be fixed on 1.3. Same applies for vehicle trenches.   
This mod is currently being integrated into ACE. There the trench building process will be fine as you requested. This port will also address the issue of the sea texture being applied.

**Comment by blackyesp** [comment]
Yeah sorry for that and I'm glad to hear all that! Congrats for joining the ACE team! Weiter so! :)

**Comment by chris579** [comment]
Well we never joined the ACE team. We are just contributing stuff like over 150 people too.

**Comment by blackyesp** [comment]
¯\_(ツ)_/¯
