### ISSUE TITLE
Textures Not Applied

### ISSUE THREAD

**Issue by JHill29th** [gruppe-adler/grad_trenches#29]
The objects don't seem to be taking on the texture of surrounding terrain at all.
While moving the object around and as you walk it changes texture based on the terrain type you are currently on but, as soon as you click "Confirm Dig" the texture changes to some really horrid texture.

![Before Digging](http://puu.sh/z46HI/4bfdfa7af8.jpg "Before Digging")
![Horrid Texture](http://puu.sh/z46DB/8e8497a832.jpg "After Digging")

[Server .rpt](https://www.dropbox.com/s/dx3xzj4mx9ti5ps/arma3server_x64_COMPANY_2018-01-18_01-05-10.7z?dl=0)

**Comment by AdlerSalbei** [comment]
Is a known bug and will be fixed in the ACE include.

**Comment by chris579** [comment]
This is covered by version 1.4.2
