### ISSUE TITLE
3den issues with trenches

### ISSUE THREAD

**Issue by gandjustas** [gruppe-adler/grad_trenches#37]
1.  Tranches placed in editor disaaper after someone tries to dig\remove them.
2.  Small and Big trenches is not visible in 3den
3.  ACE+GRAD trenches should have separate categiory in editor for discoverability.

**Comment by chris579** [comment]
1. This issue is known and cannot be resolved by us. This is dependent on the placement logic of ACE Trenches.
2. Can't reproduce, they are visible for me.
3. I disagree. Especially when having in mind that we're trying to migrate GRAD Trenches into ACE.
