### ISSUE TITLE
Error when trying to build on surfaces with ACE_canDig property set.

### ISSUE THREAD

**Issue by Theowningone** [gruppe-adler/grad_trenches#43]
Attempting to place a trench calls `ace_trenches_fnc_canDigTrench` [here](https://github.com/gruppe-adler/grad_trenches/blob/master/addons/functions/functions/fnc_placeTrench.sqf#L53), which in turn calls `ace_common_fnc_canDig` [here](https://github.com/acemod/ACE3/blob/master/addons/trenches/functions/fnc_canDigTrench.sqf#L22), which checks `configFile>>"CfgSurfaces">>_surfaceClass>>"ACE_canDig"` [here](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_canDig.sqf#L33), that in turn returns an integer. 

The comparison logic in `grad_trenches_functions_fnc_placeTrench` expects a boolean and pulls a script error.

Error from RPT:
```
 3:34:08 Error in expression <l ace_trenches_fnc_placeCancel;
};


if !([_unit] call ace_trenches_fnc_canDigTr>
 3:34:08   Error position: <!([_unit] call ace_trenches_fnc_canDigTr>
 3:34:08   Error !: Type Number, expected Bool
 3:34:08 File x\grad_trenches\addons\functions\functions\fnc_placeTrench.sqf, line 38
```

**Comment by AdlerSalbei** [comment]
Thank you for bringing this to our attention! We'll fix this.
