### ISSUE TITLE
ACE Ausdauer regeneriert sich nicht

### ISSUE THREAD

**Issue by Pictureclass** [gruppe-adler/grad_trenches#44]
Moin,
mit der aktuellen ACE Version und der aktuellen Version eures Mods regeneriert sich die Advanced Stamina von ACE leider nicht. 
Evtl. könnt ihr da was machen. 
Viele Grüße

**Comment by AdlerSalbei** [comment]
Hi, 
kannst du mir vllt ein paar mehr Infos dazu geben, z.B. was hast du gegraben und so?

**Comment by AdlerSalbei** [comment]
Okay, das erklärt warum du denkst das es kaputt ist. Dem ist nicht so. Es dauert nur Ewigkeiten, also so 10min+.

Das Stamina System wird über kurz oder lang überarbeitet.

**Comment by Pictureclass** [comment]
Wir haben es gestern probiert, und in 5 Minuten wurde evtl. ein Pixel regeneriert. Bist eine vollständige Regeneration geschieht, würden wir es auf 30 Minuten und mehr schätzen. Ich prüfe es gern nochmal.

**Comment by AdlerSalbei** [comment]
Hey,
genau so ist es derzeit gedacht. Ich glaub was du mir eigentlich mitteilen möchtest ist das dir der Impact zu heftig ist, oder?
