### ISSUE TITLE
ACE Fatigue Slow Regeneration

### ISSUE THREAD

**Issue by NoxNovember** [gruppe-adler/grad_trenches#45]
When digging a trench, `fnc_continueDiggingTrench.sqf` makes a calculation to change `ace_advanced_fatigue_anReserve` to a lower value, as shown [here](https://github.com/gruppe-adler/grad_trenches/blob/53f5d257e17e4451fc7bba15f1008009fbe61278/addons/functions/functions/fnc_continueDiggingTrench.sqf#L100-L105). While this does do the job of spending stamina to build trenches, this does not have any effect on the `ace_advanced_fatigue_anFatigue` QVAR. 

According to [ACE's fnc_mainloop.sqf for Advanced Fatigue](https://github.com/acemod/ACE3/blob/e5a15d200f44df5fccc0bc5575d18d80b35538dd/addons/advanced_fatigue/functions/fnc_mainLoop.sqf#L62-L69;), `ace_advanced_fatigue_anFatigue` has a direct effect on the regeneration of the value on `ace_advanced_fatigue_anReserve`. 

This leads to the incredibly slow stamina regeneration times.

`ace_advanced_fatigue_anReserve` [has a cap of 2300](https://github.com/acemod/ACE3/blob/e5a15d200f44df5fccc0bc5575d18d80b35538dd/addons/advanced_fatigue/script_component.hpp#L29) and will drop to 0. If the value goes below 0 the next [loop](https://github.com/acemod/ACE3/blob/e5a15d200f44df5fccc0bc5575d18d80b35538dd/addons/advanced_fatigue/functions/fnc_mainLoop.sqf#L18) should correct it back to 0. 

`ace_advanced_fatigue_anFatigue` goes from 0 to 1 in incremental values. Near 0 is the lowest regeneration possible, while 1 adds about 41.5 points a second to `ace_advanced_fatigue_anReserve`. As a player holds still, this value slowly decreases. As they move around, the value will increase. This creates a balance of regenerating stamina the more you spend it. 

Now that we have the technical stuff out of the way, lets get to the point. Due to `ace_advanced_fatigue_anFatigue` not being used while `ace_advanced_fatigue_anReserve` is drained while digging a trench, a player will not receive the regular amount of stamina regeneration they are used to. This creates a situation where players do not want to move to preserve stamina in case they need to sprint away, but won't gain any meaningful regeneration the longer they hold still. This leads to some odd behaviors.

For example, if a player were to go prone and crawl for about 15 seconds after draining all of their stamina, then hold still, `ace_advanced_fatigue_anFatigue` will be near the value of 1, which will cause their stamina to regenerate much faster than a player who was holding still for the same time, trying to "rest". I'm not sure if it was an intentional design to only use `ace_advanced_fatigue_anReserve` to simulate the fatigue of digging a field trench, but in doing so it breaks the regular behaviors the rest of ACE Stamina reinforces. 

From a review of ACE's code, it seems that much of the system they created relies on the [player moving](https://github.com/acemod/ACE3/blob/e5a15d200f44df5fccc0bc5575d18d80b35538dd/addons/advanced_fatigue/functions/fnc_mainLoop.sqf#L33) to create the balance of [spending](https://github.com/acemod/ACE3/blob/e5a15d200f44df5fccc0bc5575d18d80b35538dd/addons/advanced_fatigue/functions/fnc_mainLoop.sqf#L49) and [regaining stamina](https://github.com/acemod/ACE3/blob/e5a15d200f44df5fccc0bc5575d18d80b35538dd/addons/advanced_fatigue/functions/fnc_mainLoop.sqf#L54-L56). 

This is all tested by watching both functions of `ace_advanced_fatigue_anReserve` and `ace_advanced_fatigue_anFatigue` in the Extended Debug Console and spawning a man out in a field with an entrenching tool. If you immediately start digging, the effect will be worse than if you ran around till you drained most of your stamina bar, as your `ace_advanced_fatigue_anFatigue` value will be much lower.

The only apparent fix I can see for these issues is to add another calculation to `fnc_continueDiggingTrench.sqf` that causes `ace_advanced_fatigue_anFatigue` to be added upon as you build, thus preserving the balance between `ace_advanced_fatigue_anReserve` and `ace_advanced_fatigue_anFatigue`. It should give players a more consistent experience between ACE Advanced Fatigue and GRAD Trenches.

**Comment by AdlerSalbei** [comment]
Thank you for the thorough analyses of the ACE stamina system. I'll fix it.
