### ISSUE TITLE
Trench rising into sky

### ISSUE THREAD

**Issue by anfo55** [gruppe-adler/grad_trenches#47]
Grad Trench v1.5.0
CBA v3.8.0.180801
ACE 3 3.12.3
Malden

During digging, trench commences rising into the sky, eventually stopping.
Video:
https://youtu.be/9dd-fci_fRA

**Comment by AdlerSalbei** [comment]
Thank you for the report, I'll have a look at it.

**Comment by Fusselwurm** [comment]
@anfo55 did you use default addon settings for grad_trenches? if no, could you post your settings?

**Comment by anfo55** [comment]
I'm not sure what settings are available to change in the mod, in other words I downloaded it from GitHub, and loaded it like a mod along with CBA and ACE. I do use Arma3Sync to initialise my mods, however no other mods other than those listed were used.

**Comment by AdlerSalbei** [comment]
Could you send us your .rpt?

**Comment by AdlerSalbei** [comment]
Okay, you're rpt did not show me where the problem could be. If build a debug version could you use the attached version and sent me your rpt again?
[@grad_trenches.zip](https://github.com/gruppe-adler/grad_trenches/files/2418891/grad_trenches.zip)

**Comment by anfo55** [comment]
Done, please see attached
[arma3_x64_2018-09-26_17-54-50.zip](https://github.com/gruppe-adler/grad_trenches/files/2419181/arma3_x64_2018-09-26_17-54-50.zip)

**Comment by anfo55** [comment]
If it helps, I thought it would only be fair if I made sure it wasn't something on my end. This included re-downloading CBA and ACE 3 and using the vanilla Arma 3 launcher instead of Arma3Sync. No change unfortunately, trench still "floats away" :/

**Comment by AdlerSalbei** [comment]
Hey, it'S not your fault. @nomisum could also reproduce it. I'm building a emergencie patch right now.

**Comment by anfo55** [comment]
No worries, thanks for your prompt attention :)

**Comment by AdlerSalbei** [comment]
You are welcome 😁

**Comment by anfo55** [comment]
Tested using your emergency patch and all fixed: 
https://youtu.be/QvsPMJjiGwY
Thank you, please close issue if you are finished with it.

**Comment by AdlerSalbei** [comment]
The emergency patch was just the old system put in place. The new one will  have to be fixed!

**Comment by AdlerSalbei** [comment]
Fixed in version 1.5.2
