### ISSUE TITLE
isladuala3 Texture path = Invisible trenches

### ISSUE THREAD

**Issue by jones140** [gruppe-adler/grad_trenches#52]
I believe at some point Texture paths may have changed in isladuala3 
they are currently 
@Isla_Duala\addons\isladuala3\ibr\isladuala3\data\duala_grass_co.paa
in Grad_trenches they are listed
`    //Isla Duala
    class isladuala3 {
        surfaceTextureBasePath = "ibr\isladuala3\data\";
        suffix = "detail_co.paa";
        camouflageObjects[] = {};`
i believe fix is removing detail from suffix 
no expert

**Comment by AdlerSalbei** [comment]
Hi, 
so ich checked my last commits and i have not found any changes to the config entry of isla duala.
Do you have a rpt I could have a look at?

**Comment by dedmen** [comment]
Isla Duala got updated on 23rd december, the texture names might have changed in that update.

**Comment by AdlerSalbei** [comment]
Good point, I'd ahv to check that.

**Comment by topden** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1820520270
fix

**Comment by dedmen** [comment]
I'll never understand why people make fix mods on the workshop, but don't make a github PR to fix the original mod.

**Comment by jones140** [comment]
Well i provided fix in this 6 months ago geuss ppl get tired of waiting or dont check github

**Comment by dedmen** [comment]
>i provided fix in this 6 months ago

Can't see anything:
https://github.com/gruppe-adler/grad_trenches/pulls?q=is%3Aopen+is%3Apr

**Comment by jones140** [comment]
there we are
https://github.com/gruppe-adler/grad_trenches/pull/58
sorry about that
