### ISSUE TITLE
Short Trenches Problem

### ISSUE THREAD

**Issue by Chronan** [gruppe-adler/grad_trenches#53]
We just tested the newest version of this mod and the short trenches seem to not dig fully and can be shot/walked through. This was tested on multiple terrains including Altis and after the last Arma Update today.

**Comment by AdlerSalbei** [comment]
Hi, sorry for taking so long to come back to you. 
Thank you for reporting the bug, if fixed it.

**Comment by AdlerSalbei** [comment]
fixed
