### ISSUE TITLE
united sahrani Trenches invisible 

### ISSUE THREAD

**Issue by jones140** [gruppe-adler/grad_trenches#59]
All trenches on united sahrani  are invisible 
https://imgur.com/kgQhHxG
Mods
ACE+GRAD cup terrains 
possible a file path change 
i will look into it later.

**Comment by AdlerSalbei** [comment]
I'll have a look at it

**Comment by flamespinner** [comment]
We are having this issue too, for more information, or at least what I am running into, is if we go into the hills of United Sahrani, it works fine, but when we are on the beach, or where there is sand, there doesn't seem to be a texture/can't see it. It definitely seems to build it though, as it blocks from walking through where it should be.

**Comment by topden** [comment]
http://joxi.ru/xAeBg3MCgJBY7r

**Comment by nameless** [comment]
This bug still seems to be occurring on Sahrani and United Sahrani even after the update.

Tested with ACE and grad trenches
