### ISSUE TITLE
Chernorus 2020 

### ISSUE THREAD

**Issue by topden** [gruppe-adler/grad_trenches#71]
http://joxi.ru/zAN6z1WT61wwOA

**Comment by YetheSamartaka** [comment]
I confirm this issue. On Cherrnarus 2020, trenches are invisible. They block your movement, projectiles etc. but they do not have texture. Maybe surfaceTextureBasePath = "cup\terrains_a3\cup_chernarus_s\data\";
or suffix = "detail_co.paa"; has some wrong path or name.

**Comment by AdlerSalbei** [comment]
Will be fixed in the next version.

**Comment by AdlerSalbei** [comment]
Fixed
