### ISSUE TITLE
Continuing Digging breaks the trench

### ISSUE THREAD

**Issue by MonocledBadger** [gruppe-adler/grad_trenches#76]
Tested on Saint Kapaulio (not tested on others currently).

When either running out of stamina or manually cancelling the trench dig and then ACE interacting to continue building the trench - no action is taken. The trench does not continue builidng (regardless of stamina level) and it is not non interactable.

Replication Steps:
1. Start digging a trench.
2. Either manually run out of stamina or manually halt building.
3. Using ACE Interaction - Select continue digging.

This is currently on the latest version of ACE

**Comment by AdlerSalbei** [comment]
yeah, I found the problem. Will be fixed in the next version
