### ISSUE TITLE
Toggles ambient fire on servers with it off

### ISSUE THREAD

**Issue by enragedpixel** [gruppe-adler/grad_trenches#77]
On servers with ambient fire off, GRAD turns it on

Steps to reproduce
Server with no ambient fire enabled
grad trenches loaded
discharge heavy ordinance at foilage/heavy objects

**Comment by nomisum** [comment]
whats ambient fire? where is that setting to be found?

**Comment by AdlerSalbei** [comment]
Okay, now I'm curious to. What is Ambient Fire?

**Comment by AdlerSalbei** [comment]
Closing, missing info

**Comment by enragedpixel** [comment]
apologies, ambient fire is an MCC issue
