### ISSUE TITLE
The trenches remain too long "in the ground"

### ISSUE THREAD

**Issue by Elgin675** [gruppe-adler/grad_trenches#80]
When you start digging the trenches, they stay in the ground far too long before "coming out".

The most affected trench is the very small trench, which only begins to come out of the ground when 80% of the excavation is completed.

Attached are some captures to illustrate what I'm saying (screenshot when starting to view the trench) :

<a href="https://imgur.com/KAFBgiv"><img src="https://i.imgur.com/KAFBgivl.jpg" title="source: imgur.com" /></a><a href="https://imgur.com/QnLdm4m"><img src="https://i.imgur.com/QnLdm4ml.jpg" title="source: imgur.com" /></a>

<a href="https://imgur.com/gvzl2ky"><img src="https://i.imgur.com/gvzl2kyl.jpg" title="source: imgur.com" /></a><a href="https://imgur.com/jO5bUSB"><img src="https://i.imgur.com/jO5bUSBl.jpg" title="source: imgur.com" /></a>

<a href="https://imgur.com/voazBVO"><img src="https://i.imgur.com/voazBVOl.jpg" title="source: imgur.com" /></a><a href="https://imgur.com/1C2yhYk"><img src="https://i.imgur.com/1C2yhYkl.jpg" title="source: imgur.com" /></a>

<a href="https://imgur.com/3dWvtaj"><img src="https://i.imgur.com/3dWvtajl.jpg" title="source: imgur.com" /></a><a href="https://imgur.com/1fjT85R"><img src="https://i.imgur.com/1fjT85Rl.jpg" title="source: imgur.com" /></a>

<a href="https://imgur.com/opkFxlE"><img src="https://i.imgur.com/opkFxlEl.jpg" title="source: imgur.com" /></a><a href="https://imgur.com/2SLTffK"><img src="https://i.imgur.com/2SLTffKl.jpg" title="source: imgur.com" /></a>

<a href="https://imgur.com/nMF1zKa"><img src="https://i.imgur.com/nMF1zKal.jpg" title="source: imgur.com" /></a><a href="https://imgur.com/e5CgDTi"><img src="https://i.imgur.com/e5CgDTil.jpg" title="source: imgur.com" /></a>

Here's a comparison with classic ACE trenches :

<a href="https://imgur.com/V01yNtJ"><img src="https://i.imgur.com/V01yNtJl.jpg" title="source: imgur.com" /></a><a href="https://imgur.com/nuTG2PT"><img src="https://i.imgur.com/nuTG2PTl.jpg" title="source: imgur.com" /></a>

<a href="https://imgur.com/nyKUvrk"><img src="https://i.imgur.com/nyKUvrkl.jpg" title="source: imgur.com" /></a><a href="https://imgur.com/Jzcv0dH"><img src="https://i.imgur.com/Jzcv0dHl.jpg" title="source: imgur.com" /></a>

**Comment by AdlerSalbei** [comment]
I'll have a look at it

**Comment by Elgin675** [comment]
@AdlerSalbei Thank you ! It works well now, for most of the trenches ;) !
But for the smallest one, it takes about 20-30% of progress for it to start appearing.
A way to improve that ;) ?

**Comment by AdlerSalbei** [comment]
I'll have a look at it later.
