### ISSUE TITLE
Height difference between "Eden trenches" and "ingame trenches"

### ISSUE THREAD

**Issue by Elgin675** [gruppe-adler/grad_trenches#81]
There are height differences between the trenches placed in Eden, and those created in game.
For the most part it doesn't matter, but for the smallest trench, it becomes problematic.

On the left, the trench placed via Eden, on the right the trench placed ingame :

<a href="https://imgur.com/laWSB35"><img src="https://i.imgur.com/laWSB35l.jpg" title="source: imgur.com" /></a>

As you can see, ingame the loophole is placed at ground level, while the trench placed via Eden is correct.

**Comment by AdlerSalbei** [comment]
I'll check that. Thanks for the report

**Comment by AdlerSalbei** [comment]
Found the Issue and fixed it.
