### ISSUE TITLE
Unable to assist digging

### ISSUE THREAD

**Issue by info2345** [gruppe-adler/grad_trenches#84]
When attempting to assist digging a trench the option appeared however when selected the error appears and nothing happens.

Error: 
if (_condition) then {
[_handle] call CB>
20:21:41   Error position: <if (_condition) then {
[_handle] call CB>
20:21:41   Error if: Type code, expected Bool
20:21:41 File x\grad_trenches\addons\functions\functions\fnc_addDigger.sqf..., line 44
20:21:41 Error in expression <ms ["_unit", "_trench", "_condition"];

This error repeated until the game was closed.

**Comment by AdlerSalbei** [comment]
Thanks for the report. I'm all ready looking into it.

**Comment by AdlerSalbei** [comment]
Fixed
