### ISSUE TITLE
Trenches do not have default texture or are invisible.

### ISSUE THREAD

**Issue by Fuhrizen** [gruppe-adler/grad_trenches#89]
Trenches don't look like they have a default texture if a texture or compatible map is not found and instead become invisible, I'm aware that this did not happen before the new model update so was wondering if this could be looked into?

**Comment by AdlerSalbei** [comment]
It was happening before the model update. There just is no good way to avoid it. 
I'm still waiting for Dedmens Command.

**Comment by Seb105** [comment]
I am not sure if you are aware of this command, currently in the Dev Branch:

https://community.bistudio.com/wiki/surfaceTexture

**Comment by AdlerSalbei** [comment]
I'm aware of it. But it has not dropped until now :(

**Comment by Fusselwurm** [comment]
close? @AdlerSalbei

**Comment by AdlerSalbei** [comment]
Aye
