### ISSUE TITLE
Simplified Chinese Translation lost in newest release v1.5.9.9

### ISSUE THREAD

**Issue by GoldJohnKing** [gruppe-adler/grad_trenches#92]
- Title.

**Comment by AdlerSalbei** [comment]
I'm sorry, the translation is in the update, I just forgot to mention it. Will fix it asap

**Comment by GoldJohnKing** [comment]
Are you sure about that? I've double checked that the translation is not in the release, you can download the zip file on github release page by yourself and check for sure.
![屏幕截图(83)](https://user-images.githubusercontent.com/26923626/86455868-d3b4d400-bd53-11ea-8413-8fc6a8e725b1.png)

**Comment by AdlerSalbei** [comment]
You are right, added them in release 1.6.0.0
