### ISSUE TITLE
Trenches cannot be dug in ACE version 3.13.3 if using GRAD_trenches.

### ISSUE THREAD

**Issue by Seb105** [gruppe-adler/grad_trenches#93]
The option to use entrenching tools never appears.

**Comment by AdlerSalbei** [comment]
Have you updated to Trench Version1.6.0 ?

**Comment by Seb105** [comment]
> 
> 
> Have you updated to Trench Version1.6.0 ?

I am not, missed that update! Will update and test and close this issue if it starts working again.

**Comment by Seb105** [comment]
Update fixed it.
