### ISSUE TITLE
Some visual and physical issues 

### ISSUE THREAD

**Issue by barman75** [gruppe-adler/grad_trenches#97]
From the last update (v.1.6.4.0), the models becomes visible and touchable during the placement, just for a moment, for all of the players. 
See on video:
https://www.twitch.tv/videos/843093740?t=00h21m20s
and later on

**Comment by AdlerSalbei** [comment]
Thanks for the report, I'll have a look at it.

**Comment by AdlerSalbei** [comment]
Fixed in #101
